### PR TITLE
Hide frames with no visible children

### LINKED ISSUE #2445: App draws little spaces for empty frames
### Actual behaviour
The app draws little spaces for frames even though all elements of the frame are not visible because of `visibility=[...]`. You can see this at the top (before the frame "Licht"):
Screenshot_20210209-151959

================================

I added a label to the Frame to test this further:
Screenshot_20210209-151950

================================

This does not only happen on top of the sitemap. I injected an empty frame after the frame "Licht" before "Steckdosen" to test this:
Screenshot_20210209-152201

### Expected behaviour
Don't draw these spaces. I guess the app should check if at least of the elements of the frame are visible currently and if not skip the entire frame.

 
### Steps to reproduce
```
sitemap smartphone label="Felix"
{
    Frame
    {
        Text item=Netzwerk_DLANStatus label="DLAN muss wiederhergestellt werden" visibility=[Netzwerk_DLANStatus==OFF]
        Text item=System_Updates_OpenHAB label="OpenHAB Update verfügbar" visibility=[System_Updates_OpenHAB!="OFF"]
        Text item=Wecker_Formatiert visibility=[Wecker_Gestellt==ON]
        Text item=System_SSH_Versuche_Fehlgeschlagen labelcolor=["red"] valuecolor=["red"] visibility=[System_SSH_Versuche_Fehlgeschlagen!=0]
        Text item=System_SSH_FehlgeschlageneIPs visibility=[System_SSH_Versuche_Fehlgeschlagen!=0]
        Switch item=System_SSH_Versuche_Fehlgeschlagen_Bestaetigen mappings=[ON="OK"] visibility=[System_SSH_Versuche_Fehlgeschlagen!=0]
    }
....
```
All of the visibility checks fail so no element is visible.

#### Client
* Android version: 11
* Device model: OnePlus 7TPro HD1913
* App version : 2.16.3-beta
* Build flavor : Full
* Device language: German

### PR DESCRIPTION
**Pull request by mueller-ma**
Fixes #2445

Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

File: mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt [hunk 1]
```diff
@@ -261,6 +261,12 @@ class WidgetAdapter(
         if (!widget.visibility) {
             return false
         }
+        if (widget.type == Widget.Type.Frame) {
+            // Hide frames with no visible children
+            return items
+                .filter { it.parentId == widget.id }
+                .any { it.visibility }
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt:268]: This should only return false if there's no visible child, and otherwise defer to the lines below. Otherwise a non-enpty frame will be shown even if one of its parents is invisible (even though I know this is a theoretical case).

Comment (mueller-ma) [reply mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt:268]: Yes, I saw this issue as well. Since we don't have nested frames, this shouldn't be an issue, but I can change it.

Comment (mueller-ma) [reply mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt:268]: Maybe the function should be renamend now? `shouldShowWidget`?

**Review by maniac103 — APPROVED** [review]
