### PR TITLE
Preserve authentication information over HTTP redirects.

### LINKED ISSUE #1212: Does not send basic authentication for access to events (reverse proxy)
### Actual behaviour
I am using openHAB 2.4 behind a reverse SSL proxy with basic authenticaion. I can see in the Apache logs that the app does not send the credentials for this URL:

"GET /openhab/rest/sitemaps/events/0280f475-925e-463f-9227-202b094a7bd0?sitemap=default&pageid=default HTTP/1.1" 401 442

This does not happen when using the Chrome browser to access the Basic UI.

### Expected behaviour
The app should always send the credentials (or react properly to the 401).

 
### Steps to reproduce
1. Set up reverse proxy with Apache and Basic Authentication
2. Point the app to that remote URL

### Can you reproduce the issue in demo mode?
No.

#### Client
* Android version: Pie
* Device model: Xiaomi Redmi Note 5
* Stock or customized ROM: Custom, Pixel Experience
* App version : 2.5.0
* Build flavor : Play Store
* Device language: German

#### Server
* Server version: 2.4.0
* Reverse Proxy: Apache
* Authentication method : Basic Auth

#### openHAB Cloud
N/A

#### App log
```
There is no such option!?
```

#### openHAB Server log
```
Nothing in that log.
```

#### Reverse Proxy log
```
Insert your reverse proxy error log here.
For nginx: `/var/log/nginx/error.log`
For Apache 2: `/var/log/apache2/error.log`
```
Nothing in that log.
```
"GET /openhab/rest/sitemaps/events/0280f475-925e-463f-9227-202b094a7bd0?sitemap=default&pageid=default HTTP/1.1" 401 442
```

### PR DESCRIPTION
**Pull request by maniac103**
Fixes #1212

### CODE REVIEW

**Comment by maniac103** [comment]
@mueller-ma Can you check with your HTTP proxy setup whether this actually works? I don't have a proxy setup to test with.

File: mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt [hunk 1]
```diff
@@ -40,20 +40,36 @@ import java.util.concurrent.TimeUnit
...
         DEFAULT,
         AVOID_CACHE,
         FORCE_CACHE_IF_POSSIBLE
     }
 
     fun makeSse(url: HttpUrl, listener: EventSourceListener): EventSource {
-        val request = makeAuthenticatedRequestBuilder()
+        val request = Request.Builder()
             .url(url)
+            .addHeader("User-Agent", "openHAB client for Android")
```
Comment (mueller-ma) [inline mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt]: I'd make constants out of those two strings and "Authorization" above.

Comment (maniac103) [reply mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt]: Is it really that useful? I'm not sure about it. If you think we really should do it, I think I'll change it back to a common method (`makeRequestBuilder`).
For the `Authorization` string, I don't think making it a constant makes sense, as it's only used once.

Comment (mueller-ma) [reply mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt]: "Authorization" is also used in the MainActivity. I'd put it in constants as we need to use these headers for the video widgets as well (#1829) and there we cannot use a common function.

Comment (maniac103) [reply mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt]: I'd keep it as is, following the example of the okhttp internal code ¯\_(ツ)_/¯ Since those header names are well-known names in the HTTP spec, IMHO putting them behind constants makes the code harder to (immediately) understand.
