### PR TITLE
Use WorkManager to send voice commands

### LINKED ISSUE #1958: voicecommand widget not working with energysave
if you close the app by "close all" on app overwiew and then try to send voicecommand with widget, google reacts to voice, but the command is not sent to openhab and  the popup generated by the app which displays the recognized text is not showing up.

if app is closed (same scenario as before) and energy saving options for openhab are disabled, then then voice command is always sent to openhab and the popup shows up with the spoken command.

possible solutions:
1. give user a hint to disable energy saving options for openhab in system settings (open settingspage automatically at install)
2. optimize background logic

tested on android 9

### PR DESCRIPTION
**Pull request by mueller-ma**
Fixes #1958

This is mostly untested as I don't have a voice recognition app currently.

@markusuidl Do you want to test the following apk?

- Rename it to .apk
- Uninstall openHAB Beta if installed
- Install my apk

[mobile-foss-beta-debug.zip](https://github.com/openhab/openhab-android/files/4874123/mobile-foss-beta-debug.zip)

### CODE REVIEW

**Comment by markusuidl** [comment]
Ok will give this a try.

Should I enable energy optimization from Android for the app, because actually I have excluded the application from power save?

**Comment by mueller-ma** [comment]
> Should I enable energy optimization from Android for the app, because actually I have excluded the application from power save?

Yes, this shouldn't be needed any longer with this PR.

**Comment by markusuidl** [comment]
@mueller-ma had no time to uninstall and reinstall your apk, finally managed now and will test...

**Comment by markusuidl** [comment]
@mueller-ma installed your apk, works like a charm!

android system energy optimization is enabled for openhab (by default after reinstall)
placed widget to homescreen and it seems to work better now
voicecommands in app work too

voicecommands of my testing scenarios have been recognized and sent to openhab 👍

File: mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt [hunk 1]
```diff
@@ -162,6 +164,27 @@ class BackgroundTasksManager : BroadcastReceiver() {
...
             }
+            ACTION_VOICE_RESULT -> {
+                var voiceCommand = intent.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS)?.elementAtOrNull(0)
+                    ?: return
+
+                Log.i(TAG, "Recognized text: $voiceCommand")
+                context.getPrefs().getPrefixForVoice()?.let { prefix ->
+                    voiceCommand = "$prefix|$voiceCommand"
+                    Log.d(TAG, "Prefix voice command: $voiceCommand")
+                }
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt:175]: Since voice commands are handled specially anyway, why not remove adding the prefix here...

File: mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt [hunk 2]
```diff
@@ -221,6 +225,33 @@ class ItemUpdateWorker(context: Context, params: WorkerParameters) : Worker(cont
         }
     }
 
+    private fun handleVoiceCommand(connection: Connection, value: ValueWithInfo): Result {
+        val headers = mapOf("Accept-Language" to Locale.getDefault().language)
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt:229]: ... and instead do it here, which avoids the `split()` line below.

File: mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt [hunk 3]
```diff
@@ -221,6 +225,33 @@ class ItemUpdateWorker(context: Context, params: WorkerParameters) : Worker(cont
...
+                    .post("rest/voice/interpreters", value.value, headers = headers)
+                    .asStatus()
+            }
+        } catch (e: HttpClient.HttpException) {
+            if (e.statusCode == 404) {
+                Log.d(TAG, "Voice interpreter endpoint returned 404, falling back to item")
+                runBlocking {
+                    connection.httpClient
+                        .post("rest/items/VoiceCommand", value.value)
+                        .asStatus()
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt:242]: If that statement throws, the app will crash (unlike before, where there was a nested try-catch).

File: mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt (hunk 1 above)
Comment (mueller-ma) [reply mobile/src/main/java/org/openhab/habdroid/background/BackgroundTasksManager.kt]: Sure, that's a better solution.

File: mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt (hunk 3 above)
Comment (mueller-ma) [reply mobile/src/main/java/org/openhab/habdroid/background/ItemUpdateWorker.kt]: Added try/catch here
