### PR TITLE
Fix text items with newline character

### LINKED ISSUE #3814: String-Item is no more shown in any newer App-Version than 3.15.4
The String-Item was since years shown in the app and everywhere else it works, only in the new app-verssion it's without any text

*.sitemap:   `Text item=KA_AF`       
*.items:       `String KA_AF "[%s]" <waste> { channel="http:url:KA_AF:text"}`
*.things: 
```
Thing http:url:KA_AF "Abfuhrkalender" [
    baseURL="https://******",
    commandMethod="POST",
    refresh=3600]{
      Channels:
        Type string : text "Text" [ stateTransformation="JS:KA_AF.js" ]
      }

```

KA_AF*.js

```(function(i) {
    var array = i.split("BEGIN:VEVENT");
    var poi = [];
    var ausgabe = "";
    var aus = "";
    var Datum = new Date();
    var Start = new Date(Datum.getTime() + 86400000 * 7)
    for (i = 1; i < array.length; i++) {
        SUMMARY = array[i].split("SUMMARY:");
        SUMMARY = SUMMARY[1].split("\r");
        SUMMARY = SUMMARY[0].split(" in Donauw");
        SUMMARY = SUMMARY[0];
        if (array[i].indexOf("DATE:") > -1) {
            DTSTART = array[i].split("DATE:");
            DTSTART = DTSTART[1].split("\r");
            DTSTART = calenDayTo(DTSTART[0]);
            DTEND = new Date(DTSTART.getTime() + 86400000)
        } else {
            DTSTART = array[i].split("DTSTART:");
            DTSTART = DTSTART[1].split("\r");
            DTSTART = calenDateTo(DTSTART[0]);
            DTEND = array[i].split("DTEND:");
            DTEND = DTEND[1].split("\r");
            DTEND = calenDateTo(DTEND[0]);
        }
        if (Start >= DTSTART && Datum <= DTEND) {
            startdiff = DTSTART.getTime() - Datum.getTime() + Datum.getHours() * 3600000 + Datum.getMinutes() * 60000 + Datum.getSeconds() * 1000;
            startdiff = startdiff / 86400000;
            startdiff = Math.round(startdiff);
            poi.push([startdiff, SUMMARY]);
        }
    };
    poi.sort(function(a, b) {
        return a[0] - b[0];
    });
    for (i = 0; i < poi.length; i++) {
        ausgabe += poi[i][1];
        j = 0;
        if (i + 1 < poi.length) {
            if (poi[i][0] == poi[i + 1][0]) {
                j = 1;
            }
        }
        if (j == 1) {
            ausgabe += " und ";
        } else if (poi[i][0] == 0) {
            ausgabe += " heute";
        } else if (poi[i][0] == 1) {
            ausgabe += " morgen";
        } else {
            ausgabe += " " + poi[i][0] + " Tage";
        }
        if (j != 1 && i + 1 < poi.length) {
            ausgabe += ",\n";
        }
    }
    return ausgabe;
})(input);

function calenDayTo(DT) {
    var DTY = DT.substr(0, 4);
    var DTM = DT.substr(4, 2) - 1;
    var DTT = DT.substr(6, 2);
    var DT2 = new Date(DTY, DTM, DTT, 0, 0, 0);
    return DT2;
}

function calenDateTo(DT) {
    var DTY = DT.substr(0, 4);
    var DTM = DT.substr(4, 2) - 1;
    var DTT = DT.substr(6, 2);
    var DTS = DT.substr(9, 2);
    var DTI = DT.substr(11, 2);
    var DTE = DT.substr(13, 2);
    var DT2 = new Date(DTY, DTM, DTT, DTS, DTI, DTE);
    return DT2;
}    
     

```

String example: `Gelber Sack 2 Tage, Biotonne 4 Tage`

### PR DESCRIPTION
**Pull request by mueller-ma**
Closes #3814

### CODE REVIEW

File: mobile/src/main/java/org/openhab/habdroid/model/Widget.kt [hunk 1]
```diff
@@ -71,9 +71,14 @@ data class Widget(
     val visibility: Boolean,
     val rawInputHint: InputTypeHint?
 ) : Parcelable {
-    val label get() = rawLabel.split("[", "]")[0].trim()
+    val label get() = rawLabel.substringBefore("[").trim()
     val stateFromLabel: String? get() {
-        val value = Widget.stateLabelRegex.find(rawLabel)?.groupValues?.getOrNull(1)
+        var value: String? = rawLabel.removePrefix(label).trim()
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/model/Widget.kt:76]: Instead of using `var`, I think it would be nicer to chain using `.let()`.
