### PR TITLE
Enhance status fragments

### LINKED ISSUE #1115: Enhance "No connection" fragments
1. Add "Turn on Wifi" button if wifi is turned off and no remote connection is configured.
2. Add button and info text to enable demo mode if discovery failed.

### PR DESCRIPTION
**Pull request by mueller-ma**
* Add ability to show a second hint and/or button.

Discorvery failed:
* Discorvery failed hint and open settings button (old)
* Demo mode hint and enable demo mode button (added)

No network available:
* Enable wifi button (added)

No remote server:
If wifi is enabled:
* "No remote server configured" hint and open settings button (old)

If wifi is disabled:
* "No remote server configured" hint and open settings button (old)
* Enable wifi button (added)

Fixes #1115

Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

**Comment by maniac103** [comment]
Do you have a screenshot of how it looks now?

File: mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.java [hunk 1]
```diff
@@ -443,16 +445,19 @@ public void onAvailableConnectionChanged() {
...
-                final String message;
                 if (failureReason instanceof NetworkNotSupportedException) {
                     NetworkInfo info =
                             ((NetworkNotSupportedException) failureReason).getNetworkInfo();
-                    message = getString(R.string.error_network_type_unsupported,
-                            info.getTypeName());
+                    mController.indicateNoNetwork(
+                            getString(R.string.error_network_type_unsupported, info.getTypeName()));
+                } else if (failureReason instanceof NetworkNotAvailableException
+                        && !((WifiManager) getSystemService(Context.WIFI_SERVICE))
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.java]: I'd prefer to fetch the WifiManager instance out of the if-else cascade (e.g. in line 448), in order to make the code more clear/readable.

File: mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java [hunk 2]
```diff
@@ -232,16 +235,31 @@ public void indicateNoNetwork(CharSequence message) {
         mActivity.updateTitle();
     }
 
+    /**
+     * Indicate to the user that no network connectivity is present and Wi-Fi is disabled.
+     *
+     * @param message Error message to show
+     */
+    public void indicateEnableWifiNetwork(CharSequence message) {
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java]: Couldn't this be solved by an additional parameter to `indicateNoNetwork` (e.g. `shouldSuggestEnablingWifi`)

File: mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java [hunk 3]
```diff
@@ -543,99 +561,125 @@ protected static int determineTransition(FragmentUpdateReason reason) {
...
-            CharSequence message = arguments.getCharSequence("message");
-            if (!TextUtils.isEmpty(message)) {
-                descriptionText.setText(message);
-            } else {
-                descriptionText.setVisibility(View.GONE);
+            boolean needsOr = false;
+            if (setDescription(arguments, view, R.id.description1, KEY_MESSAGE_1)
+                    & setDescription(arguments, view, R.id.description2, KEY_MESSAGE_2)) {
+                needsOr = true;
             }
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java]: boolean needsOr = setDescription(...) && setDescription(...);

File: mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java [hunk 4]
```diff
@@ -646,16 +690,77 @@ public View onCreateView(@NonNull LayoutInflater inflater,
                 watermark.setVisibility(View.GONE);
             }
 
-            final Button button = view.findViewById(R.id.button);
-            int buttonTextResId = arguments.getInt("buttontext");
+            if (initButton(arguments, view, R.id.button1, KEY_BUTTON_1_TEXT, KEY_BUTTON_1_TAG)
+                    & initButton(arguments, view, R.id.button2, KEY_BUTTON_2_TEXT,
+                    KEY_BUTTON_2_TAG)) {
+                needsOr = true;
+            }
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java]: As above.

File: mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java [hunk 5]
```diff
@@ -646,16 +690,77 @@ public View onCreateView(@NonNull LayoutInflater inflater,
...
+                WifiManager wifiManager =
+                        (WifiManager) getContext().getSystemService(Context.WIFI_SERVICE);
+                wifiManager.setWifiEnabled(true);
+            } else if (view.getTag().equals(BUTTON_TAG_RETRY_NETWORK)) {
+                ConnectionFactory.restartNetworkCheck();
+                getActivity().recreate();
+            } else if (view.getTag().equals(BUTTON_TAG_RETRY_SERVER_PROP_FETCH)) {
+                ((MainActivity) getActivity()).retryServerPropertyQuery();
+            }
+        }
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java]: Could use a lambda for each of the cases, assign the lambda as tag and execute it in onClick. Would save the indirection.

Comment (mueller-ma) [reply mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java]: Some actions are used more than once, e.g. enable wifi and open settings. This is why I put everything in this function.

**Comment by maniac103** [comment]
Having now looked at the new layout, I fail to like it :-/ The 'or' text looks out of place IMHO, and so does the second description text.
I'd prefer if we dropped the 'or' text and keep a single help text for each of the cases, which just becomes longer if there's a second button, and then place the buttons right below each other (phone) or next to each other (tablet?).

To give a wording example, in the 'discovery failed' case I'd suggest something like `We didn't find an openHAB server in your network. If you already have a server, please configure its IP address or host name in the server settings. If you don't yet have a server, you can enable demo mode to see what openHAB is capable of.` (and then have the two buttons below that).

File: mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.java [hunk 6]
```diff
@@ -136,7 +138,7 @@
     private Uri mPendingNfcData;
     private String mPendingOpenedNotificationId;
     private Sitemap mSelectedSitemap;
-    private ContentController mController;
+    public ContentController mController;
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.java]: Should keep this private.

File: mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java [hunk 7]
```diff
@@ -543,99 +554,115 @@ protected static int determineTransition(FragmentUpdateReason reason) {
     public static class CommunicationFailureFragment extends StatusFragment {
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java]: The whole reason for the existence of those classes is/was the different onClick implementation. Could nuke them with the current impl. What I think I'd prefer, though, is
- having action implementation methods in the base class (`enableWifi()`, `enableDemoMode()` etc.)
- keep the onClick implementations in the sub classes and make those call the base class methods
- nuke the button tags

That way it's more obvious what's going on (less indirections), and the argument list for the fragment becomes shorter.

File: mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java [hunk 8]
```diff
@@ -543,99 +554,115 @@ protected static int determineTransition(FragmentUpdateReason reason) {
...
             View view = inflater.inflate(R.layout.fragment_status, container, false);
-
-            TextView descriptionText = view.findViewById(R.id.description);
-            CharSequence message = arguments.getCharSequence("message");
-            if (!TextUtils.isEmpty(message)) {
-                descriptionText.setText(message);
-            } else {
-                descriptionText.setVisibility(View.GONE);
-            }
+            setDescription(arguments, view, R.id.description, KEY_MESSAGE);
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java]: Could restore original code here now that we have only one description.

File: mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java [hunk 9]
```diff
@@ -646,16 +673,74 @@ public View onCreateView(@NonNull LayoutInflater inflater,
...
+            } else if (view.getTag().equals(BUTTON_TAG_ENABLE_DEMO_MODE)) {
+                PreferenceManager.getDefaultSharedPreferences(getContext())
+                        .edit()
+                        .putBoolean(Constants.PREFERENCE_DEMOMODE, true)
+                        .apply();
+            } else if (view.getTag().equals(BUTTON_TAG_ENABLE_WIFI)) {
+                WifiManager wifiManager = (WifiManager)
+                        getContext().getApplicationContext().getSystemService(Context.WIFI_SERVICE);
+                wifiManager.setWifiEnabled(true);
+                ((MainActivity) getActivity()).mController.updateConnection(null,
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java]: `((MainActivity) getActivity()).mController` equals `this`, so you can omit it and just call `updateConnection`

File: mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java (hunk 8 above)
Comment (mueller-ma) [reply mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java]: Will do

File: mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java (hunk 9 above)
Comment (mueller-ma) [reply mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java]: Without refactoring `this` is the onClickListener.

File: mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java (hunk 7 above)
Comment (mueller-ma) [reply mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java]: I added the tags, because in MissingConfigurationFragment the buttons can have different actions based on hasWifiEnabled and resolvedAttempted. I can re-add the onClick() functions in all fragments, but then I need to split MissingConfigurationFragment in three fragments.

File: mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java (hunk 9 above)
Comment (maniac103) [reply mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java]: Oops, right. I thought I had attempted that refactoring, but it looks like I failed at it.
I'll have a look at how to refactor this, I really don't like making `mController` public.

File: mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java (hunk 7 above)
Comment (maniac103) [reply mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java]: You don't ;-) I'll upload a suggestion to my repo.

File: mobile/src/main/res/layout/fragment_status.xml [hunk 10]
```diff
@@ -1,48 +1,66 @@
...
-        android:id="@+id/image"
-        android:layout_width="100dp"
-        android:layout_height="wrap_content"
-        android:layout_gravity="center"
-        android:adjustViewBounds="true"
-        android:gravity="center"
-        android:scaleType="fitXY"
-        android:src="@drawable/ic_signal_cellular_off_black_24dp"
-        tools:ignore="contentDescription"/>
+<ScrollView
```
Comment (maniac103) [inline mobile/src/main/res/layout/fragment_status.xml]: Is the ScrollView still needed? I still think we should avoid the need for scrolling in those views.

File: mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java (hunk 7 above)
Comment (maniac103) [reply mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.java]: https://github.com/maniac103/openhab.android/commit/dee4267e5022a335df14f3f442649fe41da5ce48 would be my suggestion.

File: mobile/src/main/res/layout/fragment_status.xml (hunk 10 above)
Comment (mueller-ma) [reply mobile/src/main/res/layout/fragment_status.xml]: I have no device where the view is scrollable, but IMO it's better to have a safeguard for extra small devices.

Comment (maniac103) [reply mobile/src/main/res/layout/fragment_status.xml]: What's the smallest screen size we (want to) support? Since our min API level is ICS I'd say 4 or 4.3 inch?
(I want to double check with emulator)

Comment (mueller-ma) [reply mobile/src/main/res/layout/fragment_status.xml]: Even if it's ok in English, it might be too much text in other languages.
