### PR TITLE
Fix crash in bottom sheet slider

### LINKED ISSUE #3150: Value(17.5) must be equal to valueFrom(0.0) plus a multiple of stepSize(1.0) when using stepSize(1.0)
### Actual behaviour
I have a number item with min=0, max=30 and step=1. The item value has been changed by a binding to 17.5. When I open the slider bottom sheet of a setpoint widget linked to that item, the app crashes:
````
java.lang.IllegalStateException: Value(17.5) must be equal to valueFrom(0.0) plus a multiple of stepSize(1.0) when using stepSize(1.0)
	at com.google.android.material.slider.BaseSlider.validateValues(BaseSlider.java:569)
	at com.google.android.material.slider.BaseSlider.validateConfigurationIfDirty(BaseSlider.java:618)
	at com.google.android.material.slider.BaseSlider.maybeCalculateTicksCoordinates(BaseSlider.java:1661)
	at com.google.android.material.slider.BaseSlider.updateTrackWidth(BaseSlider.java:1682)
	at com.google.android.material.slider.BaseSlider.onSizeChanged(BaseSlider.java:1652)
````

### Expected behaviour
The app shouldn't crash and set the slider to 17 or 18.

 ### Environment data
#### Client
* App version : [2.23.10-beta](https://github.com/openhab/openhab-android/releases/tag/2.23.10-beta)

### PR DESCRIPTION
**Pull request by mueller-ma**
Closes #3150

Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

File: mobile/src/main/java/org/openhab/habdroid/ui/ViewExtensions.kt [hunk 1]
```diff
@@ -110,3 +113,33 @@ fun RemoteViews.duplicate(): RemoteViews {
...
+
+fun Slider.setup(from: Float, to: Float, step: Float, widgetValue: Float) {
+    // Fix "The stepSize must be 0, or a factor of the valueFrom-valueTo range" exception
+    valueTo = to - (to - from).rem(step)
+    valueFrom = from
+    stepSize = step
+
+    // Fix "Value must be equal to valueFrom plus a multiple of stepSize when using stepSize"
+    val stepCount = (abs(valueTo - valueFrom) / stepSize).toInt()
+    var closetValue = valueFrom
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/ui/ViewExtensions.kt:125]: While you're at it: `closestValue`

**Review by maniac103 — APPROVED** [review]
