### PR TITLE
Fix creation of webview shortcuts

### LINKED ISSUE #2506: No creation of Homewidget for OH3 possible anymore with newest Beta
### Actual behaviour
First Problem:
On my Tablet and on my Phone i cannot create any widget for the Homescreen anymore to directly access the OH3 Main UI. 

Second Problem:
With newest Beta there should be the possibilty to choose wich page want to be choosen to link to. But this plzs button is only available on the main overview page and not visible on other pages wich are created for example ( Heating, Bathroom etc)

### Expected behaviour
With newest Beta there should be the possibility to choose the preferred page and than pushing the plus sign top right to create a widget link to the preferred page. 

 
### Steps to reproduce
Open Openhab Beta App go to OH3 Main UI and push Plzs sign in the top right corner. Widget creation should appear but doesnt.

### Can you reproduce the issue in demo mode?
Yes. Exactly same misbehaviour.

Google Pixel 4XL Android 11

Xiaomi Mi Pad 3 Android 7

### PR DESCRIPTION
**Pull request by mueller-ma**
Fixes #2506

````
W/WebView: java.lang.Throwable: A WebView method was called on thread 'JavaBridge'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 2) {44709f2} called on Looper (JavaBridge, tid 6438) {7566e81}, FYI main Looper is Looper (main, tid 2) {44709f2})
        at android.webkit.WebView.checkThread(WebView.java:2575)
        at android.webkit.WebView.getUrl(WebView.java:1251)
        at org.openhab.habdroid.ui.activity.AbstractWebViewFragment.getShortcutInfo(AbstractWebViewFragment.kt:96)
        at org.openhab.habdroid.ui.activity.AbstractWebViewFragment.pinShortcut(AbstractWebViewFragment.kt:206)
        at org.openhab.habdroid.ui.activity.AbstractWebViewFragment.access$pinShortcut(AbstractWebViewFragment.kt:70)
        at org.openhab.habdroid.ui.activity.AbstractWebViewFragment$OHAppInterfaceWithPin.pinToHome(AbstractWebViewFragment.kt:405)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2021-03-31 22:54:09.694 4816-4988/org.openhab.habdroid D/StrictMode: StrictMode policy violation: android.os.strictmode.WebViewMethodCalledOnWrongThreadViolation
        at android.webkit.WebView.checkThread(WebView.java:2575)
        at android.webkit.WebView.getUrl(WebView.java:1251)
        at org.openhab.habdroid.ui.activity.AbstractWebViewFragment.getShortcutInfo(AbstractWebViewFragment.kt:96)
        at org.openhab.habdroid.ui.activity.AbstractWebViewFragment.pinShortcut(AbstractWebViewFragment.kt:206)
        at org.openhab.habdroid.ui.activity.AbstractWebViewFragment.access$pinShortcut(AbstractWebViewFragment.kt:70)
        at org.openhab.habdroid.ui.activity.AbstractWebViewFragment$OHAppInterfaceWithPin.pinToHome(AbstractWebViewFragment.kt:405)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.os.HandlerThread.run(HandlerThread.java:67)
````

Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

File: mobile/src/main/java/org/openhab/habdroid/ui/activity/AbstractWebViewFragment.kt [hunk 1]
```diff
@@ -91,8 +93,10 @@ abstract class AbstractWebViewFragment : Fragment(), ConnectionFactory.UpdateLis
                 .putExtra(MainActivity.EXTRA_SERVER_ID, context.getPrefs().getActiveServerId())
                 .setAction(shortcutAction)
 
-            webView?.url?.toHttpUrlOrNull()?.let {
-                intent.putExtra(MainActivity.EXTRA_SUBPAGE, it.toRelativeUrl())
+            Handler(Looper.getMainLooper()).post {
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/ui/activity/AbstractWebViewFragment.kt:96]: Should use coroutines here instead of Handler.
(And BTW, I think it would be good to replace the various `GlobalScope.launch` calls in this file by making the fragment a scope by itself, and moving the `launch` calls to the respective JS interfaces.)

File: mobile/src/main/java/org/openhab/habdroid/ui/activity/AbstractWebViewFragment.kt [hunk 2]
```diff
@@ -91,8 +95,10 @@ abstract class AbstractWebViewFragment : Fragment(), ConnectionFactory.UpdateLis
                 .putExtra(MainActivity.EXTRA_SERVER_ID, context.getPrefs().getActiveServerId())
                 .setAction(shortcutAction)
 
-            webView?.url?.toHttpUrlOrNull()?.let {
-                intent.putExtra(MainActivity.EXTRA_SUBPAGE, it.toRelativeUrl())
+            launch {
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/ui/activity/AbstractWebViewFragment.kt:98]: Instead of this and the below launch block, wouldn't it be better (and more consistent) to put the `pinShortcut` call in the JS interface into a launch block?

Comment (mueller-ma) [reply mobile/src/main/java/org/openhab/habdroid/ui/activity/AbstractWebViewFragment.kt]: Yes, makes sense.

File: mobile/src/main/java/org/openhab/habdroid/ui/activity/AbstractWebViewFragment.kt [hunk 3]
```diff
@@ -202,7 +206,7 @@ abstract class AbstractWebViewFragment : Fragment(), ConnectionFactory.UpdateLis
         val context = context ?: return
         askForShortcutTitle(context, shortcutInfo) {
             val success = ShortcutManagerCompat.requestPinShortcut(context, it, null)
-            GlobalScope.launch {
+            launch {
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/ui/activity/AbstractWebViewFragment.kt:209]: Is this `launch` call actually needed (anymore)? AFAICT the callbakc should be launched in the main thread anyway.

Comment (mueller-ma) [reply mobile/src/main/java/org/openhab/habdroid/ui/activity/AbstractWebViewFragment.kt]: I remove the `launch` and used toasts below. On my device the app is closed directly after pinning a shortcut and
therefore the Snackbar is shown, but never seen by the user.

Comment (mueller-ma) [reply mobile/src/main/java/org/openhab/habdroid/ui/activity/AbstractWebViewFragment.kt]: Maybe it's not a real issue when the success snackbar isn't shown: My device minimizes the app, scrolls to the page where the shortcut is and animates it. This way the user known that the shortcut has been created.

Comment (mueller-ma) [reply mobile/src/main/java/org/openhab/habdroid/ui/activity/AbstractWebViewFragment.kt]: Reverted

Comment (mueller-ma) [reply mobile/src/main/java/org/openhab/habdroid/ui/activity/AbstractWebViewFragment.kt]: I reverted the change to Toasts. The error snackbar is also shown without the `launch` before.
