### PR TITLE
Fix HTTP response body leaks.

### LINKED ISSUE #1560: HTTP response body leak
Latest git master as of today yields the following in logcat:
```
09-28 21:15:35.086 12666 22297 W System  : A resource failed to call response.body().close(). 
09-28 21:15:35.086 12666 22297 I chatty  : uid=10211(org.openhab.habdroid) OkHttp Connecti identical 6 lines
09-28 21:15:35.086 12666 22297 W System  : A resource failed to call response.body().close(). 
```

I'll investigate this...

### PR DESCRIPTION
**Pull request by maniac103**
Fixes #1560

### CODE REVIEW

**Comment by maniac103** [comment]
Need to additionally update OkSse here: https://github.com/heremaps/oksse/issues/17

File: mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt [hunk 1]
```diff
@@ -128,6 +128,7 @@ class HttpClient constructor(private val client: OkHttpClient, baseUrl: String?,
 
                 when {
                     !response.isSuccessful -> {
+                        body?.let { it.close() }
```
Comment (mueller-ma) [inline mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt]:
```suggestion
                        body?.close()
```

Comment (maniac103) [reply mobile/src/main/java/org/openhab/habdroid/util/HttpClient.kt]: Fixed, not sure what I was thinking.
