### PR TITLE
Fix url validation in UrlInputPreference

### LINKED ISSUE #1825: DefaultConnection: IllegalArgumentException hostname can't be null
````
Fatal Exception: java.lang.IllegalArgumentException: hostname can't be null
       at java.net.InetSocketAddress.checkHost(InetSocketAddress.java:150)
       at java.net.InetSocketAddress.<init>(InetSocketAddress.java:231)
       at org.openhab.habdroid.core.connection.DefaultConnection.isReachableViaNetwork(DefaultConnection.kt:49)
       at org.openhab.habdroid.core.connection.ConnectionFactory.checkAvailableConnection(ConnectionFactory.kt:331)
       at org.openhab.habdroid.core.connection.ConnectionFactory$triggerConnectionUpdateIfNeeded$1$result$1.invokeSuspend(ConnectionFactory.kt:267)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
````

2.11.17-beta

### PR DESCRIPTION
**Pull request by mueller-ma**
It was possible to enter invalid urls like ´http:/example.com´.

> Instances of [HttpUrl] are well-formed and always have a scheme, host, and path. With
> `java.net.URL` it's possible to create an awkward URL like `http:/` with scheme and path but no
> hostname. Building APIs that consume such malformed values is difficult!

from HttpUrl.kt docs

Fixes #1825

Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

File: mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt [hunk 1]
```diff
@@ -85,16 +85,17 @@ fun String.obfuscate(clearTextCharCount: Int = 3): String {
     return substring(0, clearTextCharCount) + "*".repeat(length - clearTextCharCount)
 }
 
-fun String?.toNormalizedUrl(): String {
+fun String?.toNormalizedUrl(): String? {
     return try {
-        val url = URL(orEmpty())
-            .toString()
+        val url = toString()
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt]: `toString()` for a string? ;-)
Just use `this`.

Comment (mueller-ma) [reply mobile/src/main/java/org/openhab/habdroid/util/ExtensionFuncs.kt]: Fixed :)

**Comment by ewaldc** [comment]
Hello,
This change invalides short URI's like _/rest/sitemaps/demos_ which were working until recently.
IMHO according to RFC 2396 a valid URI is defined as:
`URI = scheme:[//authority]path[?query][#fragment]`
where the authority component divides into three subcomponents:
`authority = [userinfo@]host[:port]`

Hence, short URI should be considered valid which the current toHttpUrl (OrNull) code does not accept and considers invalid.

**Comment by mueller-ma** [comment]
Can you explain where exactly this is an issue?

**Comment by ewaldc** [comment]
Sure, see issue #2001
