### PR TITLE
Catch IOException when attempting FCM registration.

### LINKED ISSUE #1426: java.io.IOException: INVALID_SENDER
````
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done + 354(AsyncTask.java:354)
       at java.util.concurrent.FutureTask.finishCompletion + 383(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException + 252(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run + 271(FutureTask.java:271)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1167(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 641(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run + 764(Thread.java:764)
Caused by java.io.IOException: INVALID_SENDER
       at com.google.firebase.iid.zzk.zza + 66(com.google.firebase:firebase-iid@@19.0.1:66)
       at com.google.firebase.iid.zzk.zza + 79(com.google.firebase:firebase-iid@@19.0.1:79)
       at com.google.firebase.iid.zzo.then + 4(com.google.firebase:firebase-iid@@19.0.1:4)
       at com.google.android.gms.tasks.zzd.run + 5(Unknown Source:5)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1167(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 641(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run + 764(Thread.java:764)
````

Multiple Android versions, multiple devices, Version 2.7.10-beta.

### PR DESCRIPTION
**Pull request by maniac103**
Closes #1426

### CODE REVIEW

File: mobile/src/full/java/org/openhab/habdroid/core/FcmRegistrationService.kt [hunk 1]
```diff
@@ -66,6 +67,9 @@ class FcmRegistrationService : JobIntentService() {
                 } catch (e: HttpClient.HttpException) {
```
Comment (mueller-ma) [inline mobile/src/full/java/org/openhab/habdroid/core/FcmRegistrationService.kt]: Can Kotlin catch multiple exceptions in one `catch` block?

Comment (maniac103) [reply mobile/src/full/java/org/openhab/habdroid/core/FcmRegistrationService.kt]: Unfortunately not (yet): https://youtrack.jetbrains.com/issue/KT-7128
