### PR TITLE
Several preference screen improvements

### LINKED ISSUE #934: Hide preferences when they are unused in a flavor
The full screen setting is (or should be, it doesn't work) hidden when running a device with Android 4.4 or lower: https://github.com/openhab/openhab-android/blob/master/mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java#L230
This should be done for the ringtone settings as well.

### PR DESCRIPTION
**Pull request by mueller-ma**
* Disable preferences if unsupported:
  * Android version too low
  * FOSS flavor
  * openHAB 1
* Show summary for connection subscreens indicating whether the connection is unsecure
* Show summary for notification ring tone
* Rename removeProtocollFromUrl to getHostFromUrl

Fixes #934

Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

TODO:

- [x] update connection summary when connection changes.

### CODE REVIEW

File: mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java [hunk 1]
```diff
@@ -224,17 +243,86 @@ public boolean onPreferenceClick(Preference preference) {
...
+            });
+
+            final PreferenceScreen ps = getPreferenceScreen();
+
+            // Fullscreen is not supoorted in Android < 4.4
+            if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.KITKAT) {
+                Preference fullscreenPreference = ps.findPreference(Constants.PREFERENCE_FULLSCREEN);
+                fullscreenPreference.setEnabled(false);
+                fullscreenPreference.setSummary(R.string.settings_disabled_kitkat);
+            }
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java]: I'd keep this removed. There's nothing the user can do anyway.

Comment (mueller-ma) [reply mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java]: Removing settings didn't work for me at all and I think it's better to give the user feedback why it's not supported.

File: mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java [hunk 2]
```diff
@@ -224,17 +243,86 @@ public boolean onPreferenceClick(Preference preference) {
...
+
+            if (mOpenhabVersion == 1) {
+                Preference iconFormatPreference =
+                        ps.findPreference(Constants.PREFERENCE_ICON_FORMAT);
+                iconFormatPreference.setEnabled(false);
+                iconFormatPreference.setSummary(R.string.settings_disabled_openhab_1);
+                Preference chartScalingPreference =
+                        ps.findPreference(Constants.PREFERENCE_CHART_SCALING);
+                chartScalingPreference.setEnabled(false);
+                chartScalingPreference.setSummary(R.string.settings_disabled_openhab_1);
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java]: Same applies here, just hide those.

File: mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java [hunk 3]
```diff
@@ -224,17 +243,86 @@ public boolean onPreferenceClick(Preference preference) {
...
+            final PreferenceScreen ps = getPreferenceScreen();
+
+            // Fullscreen is not supoorted in Android < 4.4
+            if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.KITKAT) {
+                Preference fullscreenPreference = ps.findPreference(Constants.PREFERENCE_FULLSCREEN);
+                fullscreenPreference.setEnabled(false);
+                fullscreenPreference.setSummary(R.string.settings_disabled_kitkat);
+            }
+
+            removeUnsupportedPrefs(ps);
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java]: Why not move the remove code here and base it on CloudMessagingHelper.isSupported()?

File: mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java [hunk 4]
```diff
@@ -224,17 +243,86 @@ public boolean onPreferenceClick(Preference preference) {
...
+
+        public void updateConnectionSummary(boolean isRemote) {
+            String subscreenPrefValue = isRemote ? Constants.SUBSCREEN_REMOTE_CONNECTION
+                    : Constants.SUBSCREEN_LOCAL_CONNECTION;
+            String urlPrefValue = isRemote ? Constants.PREFERENCE_REMOTE_URL
+                    : Constants.PREFERENCE_LOCAL_URL;
+            String userPrefValue = isRemote ? Constants.PREFERENCE_REMOTE_USERNAME
+                    : Constants.PREFERENCE_LOCAL_USERNAME;
+            String passwordPrefValue = isRemote ? Constants.PREFERENCE_REMOTE_PASSWORD
+                    : Constants.PREFERENCE_LOCAL_PASSWORD;
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java]: Could pass the 4 key names as parameters here ... that way it would be a bit more clear at the caller side what's going on.

File: mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java [hunk 5]
```diff
@@ -224,17 +243,86 @@ public boolean onPreferenceClick(Preference preference) {
...
+            Preference pref = findPreference(subscreenPrefValue);
+            String url = pref.getSharedPreferences().getString(urlPrefValue, "");
+            String user = pref.getSharedPreferences().getString(userPrefValue, "");
+            String password = pref.getSharedPreferences().getString(passwordPrefValue, "");
+            String summary;
+            if (TextUtils.isEmpty(url)) {
+                summary = getString(R.string.info_not_set);
+            } else {
+                if (url.startsWith("https://") && ! TextUtils.isEmpty(user)
+                        && ! TextUtils.isEmpty(password)) {
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java]: I'd suggest differentiating between 'secure' (http vs. https) and 'authenticated'. E.g. `Connected securely to xyz.com, using authentication`

File: mobile/src/main/res/values/strings.xml [hunk 6]
```diff
@@ -61,6 +59,10 @@
     <string name="settings_notification_vibration_value_short" translatable="false">short</string>
     <string name="settings_notification_vibration_value_long" translatable="false">long</string>
     <string name="settings_notification_vibration_value_twice" translatable="false">twice</string>
+    <string name="settings_disabled_kitkat">Fullscreen is only available in Android 4.4 and above</string>
+    <string name="settings_disabled_openhab_1">Preference isn\'t available for openHAB 1</string>
+    <string name="settings_connection_summary">Connected to %s</string>
+    <string name="settings_insecure_connection_summary">Insecurly connected to %s</string>
```
Comment (maniac103) [inline mobile/src/main/res/values/strings.xml]: insecurely

File: mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java (hunk 3 above)
Comment (mueller-ma) [reply mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java]: Initially I wanted to keep the "Not supported in foss" string in the foss strings file.

File: mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java (hunk 4 above)
Comment (mueller-ma) [reply mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java]: Done

File: mobile/src/main/res/values/strings.xml (hunk 6 above)
Comment (mueller-ma) [reply mobile/src/main/res/values/strings.xml]: Done

File: mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java (hunk 5 above)
Comment (mueller-ma) [reply mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java]: IMO a non-authenticated https connection is pretty useless. An attacker can see the certificate cn during the handshake and visit the page. I guess it's not clear for every user why the "secure" connection isn't secure.

File: mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java (hunk 1 above)
Comment (maniac103) [reply mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java]: > I think it's better to give the user feedback why it's not supported.

And what is the user supposed to do with that information? I'm all for informing the user, but if he can't do anything about it, it IMHO just adds clutter.

File: mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java (hunk 3 above)
Comment (maniac103) [reply mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java]: Fair enough, but like mentioned in the other comment, I'd rather remove the preference completely. IMHO it's sufficient to inform the user about the existence of the full build in one place.

File: mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java [hunk 7]
```diff
@@ -224,17 +250,111 @@ public boolean onPreferenceClick(Preference preference) {
...
+                    return root;
+                if (PreferenceGroup.class.isInstance(p))
+                {
+                    PreferenceGroup parent = getParent((PreferenceGroup)p, preference);
+                    if (parent != null)
+                        return parent;
+                }
+            }
+            return null;
+        }
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java]: Nit: should fix curly braces in those two methods (put starting ones on old line, add missing ones)

File: mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java [hunk 8]
```diff
@@ -224,17 +250,111 @@ public boolean onPreferenceClick(Preference preference) {
...
+         * @author https://stackoverflow.com/a/17633389
+         */
+        private PreferenceGroup getParent(PreferenceGroup root, Preference preference)
+        {
+            for (int i = 0; i < root.getPreferenceCount(); i++)
+            {
+                Preference p = root.getPreference(i);
+                if (p == preference)
+                    return root;
+                if (PreferenceGroup.class.isInstance(p))
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java]: `p instanceof PreferenceGroup`?

File: mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java (hunk 7 above)
Comment (mueller-ma) [reply mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java]: Done

File: mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java (hunk 8 above)
Comment (mueller-ma) [reply mobile/src/main/java/org/openhab/habdroid/ui/OpenHABPreferencesActivity.java]: Done

**Comment by mueller-ma** [comment]
The connection summary isn't updated when the connection setting changes. Any ideas how to implement that? Setting `setOnPreferenceChangeListener` in `updateAndInitPreferences()` for the url, user and pw fields doesn't work as they are on a subpage.

**Comment by maniac103** [comment]
Update them in 'onResume()'?
