### PR TITLE
Fix image refresh regressions

### LINKED ISSUE #985: Image refresh broken
### Actual behaviour
Image items without the refresh parameter doen't refresh, when swiped-to-refresh.

### Expected behaviour
They should refresh.

#### Client
* Android version: Android 7.1.2
* Device model: Moto G4
* Stock or customized ROM: LineageOS 14
* App version : 2.2.19
* Build flavor : Foss
* Device language: de

@maniac103 I experience this issue on multiple devices, but have no time to debug it right now.

### PR DESCRIPTION
**Pull request by maniac103**
- Correctly refresh images after pull-to-refresh
- Correctly resume image refresh when reusing views

Fixes #985

### CODE REVIEW

File: mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.java [hunk 1]
```diff
@@ -308,12 +304,15 @@ public void execute(boolean avoidCache) {
...
             }
         }
 
+        public boolean hasCompleted() {
+            return mCall == null;
+        }
+
         public boolean isActiveForUrl(HttpUrl url) {
-            return mCall != null && mCall.request().url().equals(url);
+            return mCall != null && mCall.request().url().equals(url) && !mCall.isCanceled();
```
Comment (mueller-ma) [inline mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.java]: `return !hasCompleted() ...`?

Comment (maniac103) [reply mobile/src/main/java/org/openhab/habdroid/ui/widget/WidgetImageView.java]: I went a bit back and forth about this (started splitting the call to `isActiveForUrl()` into `!hasCompleted() && matchesUrl(url)`), but ultimately figured keeping it the way it is is the most readable/simple solution. If you have strong feelings about it though, I can change it.
