### PR TITLE
Show sitemap selection dialog after clearing it in the settings

### LINKED ISSUE #902: Clearing default sitemap takes affect after restarting the app
### Actual behaviour
Clearing default sitemap takes affect after restarting the app

### Expected behaviour
Should take affect w/o restarting

 
### Steps to reproduce
1. Select a default sitemap
2. Open settings
3. Clear default sitemap
4. Go back
5. You should be asked

### Can you reproduce the issue in demo mode?

No, only one sitemap

#### Client
* Android version: Android 7.1
* Device model: Oneplus X
* Stock or customized ROM: LineageOS 14.1
* App version : 2.2.0
* Build flavor : Full
* Device language: en

#### Server
Client issue

#### App log
```
Nothing to see after leaving settings
```

### PR DESCRIPTION
**Pull request by mueller-ma**
Fixes #902

Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

File: mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java [hunk 1]
```diff
@@ -398,14 +396,18 @@ public void onConfigurationChanged(Configuration newConfig) {
...
         super.onResume();
+
         ConnectionFactory.addListener(this);
         MemorizingTrustManager.getInstance(this).bindDisplayActivity(this);
 
         onAvailableConnectionChanged();
         updateNotificationDrawerItem();
 
+        if (TextUtils.isEmpty(mSettings.getString(Constants.PREFERENCE_SITEMAP_NAME, ""))) {
+            loadSitemapList(true);
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java]: Why reload the sitemaps instead of only calling `showSitemapSelectionDialog()`?

File: mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java [hunk 2]
```diff
@@ -398,14 +396,24 @@ public void onConfigurationChanged(Configuration newConfig) {
...
-
         super.onResume();
+
         ConnectionFactory.addListener(this);
         MemorizingTrustManager.getInstance(this).bindDisplayActivity(this);
 
         onAvailableConnectionChanged();
         updateNotificationDrawerItem();
 
+        if (mInitState == InitState.DONE &&
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java]: Another approach that didn't occur to me earlier:
- Add an intent extra to the settings activity's result intent that flags a cleared sitemap (like for theme change)
- Check that flag in onActivityResult (check for sitemap emptiness not needed anymore at that point)

Comment (mueller-ma) [reply mobile/src/main/java/org/openhab/habdroid/ui/OpenHABMainActivity.java]: Yes, this is a lot cleaner.
