### PR TITLE
Request background location access for sending SSID

### LINKED ISSUE #2047: Wi-Fi name is UNDEF
### Actual behaviour
Wi-Fi name updates to the correct SSID name if openHAB client is in foreground, and to UNDEF in background.

### Expected behaviour
Wi-Fi name should always update to the correct SSID if Wi-Fi is connected and correct permissions are set.
 
### Steps to reproduce
1. Configure sending Wi-Fi name to OpenHAB server (both server and client).
1. Set update interval to 15 minutes (no need to wait for several hours).
1. Connect the device to Wi-Fi.
1. Run the OpenHAB app.
1. Check if server received correct SSID name.
1. Send the app to background.
1. Wait for 15 minutes.
1. Check item value at server.

### Can you reproduce the issue in demo mode?
No, since this feature is disabled in demo mode.

#### Client
* Android version: 10
* Device model: Samsung Galaxy A10 and Samsung Galaxy A40.
* App version : 2.13.0
* Build flavor : Full
* Device language: Russian

#### Server
* Server version: 2.5.5
* Reverse Proxy: nginx 1.14.2
* Authentication method : user and password (via nginx).

#### openHAB Cloud
* Self hosted cloud or myopenhab.org: None
* openHAB Cloud version : None
* Authentication method : None

I believe that OpenHAB client should request background location access on Android 10.

### PR DESCRIPTION
**Pull request by mueller-ma**
Fixes #2047

Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

File: mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt [hunk 1]
```diff
@@ -999,18 +1000,18 @@ class MainActivity : AbstractBaseActivity(), ConnectionFactory.UpdateListener {
...
 
         val missingPermissions = tasksWithPermissions
             .filter { entry ->
-                prefs.getStringOrNull(entry.key)?.toItemUpdatePrefValue()?.first == true && !hasPermission(entry.value)
+                val requiredPermissions = BackgroundTasksManager.getRequiredPermissionsForTask(entry)
+                prefs.getStringOrNull(entry)?.toItemUpdatePrefValue()?.first == true &&
+                    requiredPermissions != null && !hasPermissions(requiredPermissions)
             }
-            .map { entry -> entry.value }
+            .map { entry -> BackgroundTasksManager.getRequiredPermissionsForTask(entry) }
```
Comment (mueller-ma) [inline mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt:1014]: @maniac103 Do you have a hint for me on how to convert this list of string arrays in an array?

Comment (maniac103) [reply mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt:1014]: Didn't actually try, but I think there's `.flatten().toSet()`.

Comment (mueller-ma) [reply mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt]: `.toTypedArray().flatten().toSet()` should do it, but I haven't tested it yet. Thanks for the hint.

File: mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt [hunk 2]
```diff
@@ -999,18 +998,17 @@ class MainActivity : AbstractBaseActivity(), ConnectionFactory.UpdateListener {
...
-        val missingPermissions = tasksWithPermissions
+        val missingPermissions = BackgroundTasksManager.KNOWN_KEYS
             .filter { entry ->
-                prefs.getStringOrNull(entry.key)?.toItemUpdatePrefValue()?.first == true && !hasPermission(entry.value)
+                val requiredPermissions = BackgroundTasksManager.getRequiredPermissionsForTask(entry)
+                prefs.getStringOrNull(entry)?.toItemUpdatePrefValue()?.first == true &&
+                    requiredPermissions != null && !hasPermissions(requiredPermissions)
             }
-            .map { entry -> entry.value }
+            .mapNotNull { entry -> BackgroundTasksManager.getRequiredPermissionsForTask(entry) }
```
Comment (maniac103) [inline mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt:1007]: Can also amend a `?.toList()` for each array instead of the `toTypedArray()` below.

Comment (mueller-ma) [reply mobile/src/main/java/org/openhab/habdroid/ui/MainActivity.kt]: Sure, makes it better readable.
