### PR TITLE
Fix segmented control button

### LINKED ISSUE #1121: Switch labeled buttons are cut with older Android revisions (4.4.x)
### Actual behaviour
Switch labeled buttons are cut with older Android revisions (4.4.x)

### Expected behaviour
Full visibility of labeled buttons

 
### Steps to reproduce
1. Use labeled buttons on sitemap (mapping)
2. E.G.: Switch item=<itemname> [label="<labelname>"] [icon="<iconname>"] [mappings="<mapping definition>"]

#### Client
* Android version: 4.4.2
* Device model: Lenovo, Samsung Note 10.1
* Stock or customized ROM: Stock
* App version : 2.5.0
* Build flavor : Full
* Device language: German

screenshot_2018-12-04-06-24-11_small
screenshot_2018-12-04-06-23-24_small

### PR DESCRIPTION
**Pull request by maniac103**
Make sure buttons aren't cut off on API < 21, and clean it up a little.

Closes #1121

### CODE REVIEW

File: mobile/src/main/java/org/openhab/habdroid/ui/widget/SegmentedControlButton.java [hunk 1]
```diff
@@ -65,6 +61,7 @@ public SegmentedControlButton(Context context, AttributeSet attrs, int defStyle)
             mTextPaint.setTextSize(getTextSize());
             mTextPaint.setTextAlign(Paint.Align.CENTER);
 
+            int lineColor = a.getColor(R.styleable.SegmentedControlButton_underlineColor, 0);
```
Comment (mueller-ma) [inline mobile/src/main/java/org/openhab/habdroid/ui/widget/SegmentedControlButton.java]: Nit: Add `@ColorInt` here

Comment (maniac103) [reply mobile/src/main/java/org/openhab/habdroid/ui/widget/SegmentedControlButton.java]: Done.
