### PR TITLE
Fix typo in content controller instance state key.

### LINKED ISSUE #1428: ClassCastException in ContentController
````
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.openhab.habdroid.beta/org.openhab.habdroid.ui.MainActivity}: java.lang.ClassCastException: org.openhab.habdroid.ui.activity.ContentController$CommunicationFailureFragment cannot be cast to org.openhab.habdroid.ui.WidgetListFragment
       at android.app.ActivityThread.performLaunchActivity + 2944(ActivityThread.java:2944)
       at android.app.ActivityThread.handleLaunchActivity + 3079(ActivityThread.java:3079)
       at android.app.servertransaction.LaunchActivityItem.execute + 78(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks + 108(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute + 68(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage + 1836(ActivityThread.java:1836)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 193(Looper.java:193)
       at android.app.ActivityThread.main + 6702(ActivityThread.java:6702)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 493(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main + 911(ZygoteInit.java:911)
Caused by java.lang.ClassCastException: org.openhab.habdroid.ui.activity.ContentController$CommunicationFailureFragment cannot be cast to org.openhab.habdroid.ui.WidgetListFragment
       at org.openhab.habdroid.ui.activity.ContentController.onRestoreInstanceState + 150(ContentController.kt:150)
       at org.openhab.habdroid.ui.MainActivity.onCreate + 168(MainActivity.kt:168)
       at android.app.Activity.performCreate + 7136(Activity.java:7136)
       at android.app.Activity.performCreate + 7127(Activity.java:7127)
       at android.app.Instrumentation.callActivityOnCreate + 1271(Instrumentation.java:1271)
       at android.app.ActivityThread.performLaunchActivity + 2924(ActivityThread.java:2924)
       at android.app.ActivityThread.handleLaunchActivity + 3079(ActivityThread.java:3079)
       at android.app.servertransaction.LaunchActivityItem.execute + 78(LaunchActivityItem.java:78)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks + 108(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute + 68(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage + 1836(ActivityThread.java:1836)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 193(Looper.java:193)
       at android.app.ActivityThread.main + 6702(ActivityThread.java:6702)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 493(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main + 911(ZygoteInit.java:911)
````

Multiple Android versions, multiple devices, Version 2.7.10-beta.

### PR DESCRIPTION
**Pull request by maniac103**
Closes #1428

### CODE REVIEW

File: mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt [hunk 1]
```diff
@@ -137,7 +137,7 @@ abstract class ContentController protected constructor(private val activity: Mai
         }
         noConnectionFragment?.let { page ->
             if (page.isAdded) {
-                fm.putFragment(state, "sitemapFragment", page)
+                fm.putFragment(state, "errorFragment", page)
```
Comment (mueller-ma) [inline mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt]: I'd use a constant here.

Comment (maniac103) [reply mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt]: Not sure. It's only the two methods next to each other (`onSaveInstanceState` and `onRestoreInstanceState`) that use this; introducing constants might be more cluttering than actual help. The bug in question happened via copy'n'paste, which also could have happened with constants...

Comment (mueller-ma) [reply mobile/src/main/java/org/openhab/habdroid/ui/activity/ContentController.kt]: IMO constants should be used if the string is used more than once. This way it's pretty easy to find all usages of this string.
