### PR TITLE
Fix nullability of KeyManager callbacks.

### LINKED ISSUE #1429: IllegalArgumentException: Parameter specified as non-null is null
````
Fatal Exception: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter issuers
       at org.openhab.habdroid.core.connection.ConnectionFactory$ClientKeyManager.chooseClientAlias + 7(Unknown Source:7)
       at com.android.org.conscrypt.OpenSSLSocketImpl.chooseClientAlias + 1347(OpenSSLSocketImpl.java:1347)
       at com.android.org.conscrypt.SSLParametersImpl.chooseClientCertificate + 729(SSLParametersImpl.java:729)
       at com.android.org.conscrypt.OpenSSLSocketImpl.clientCertificateRequested + 493(OpenSSLSocketImpl.java:493)
       at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(NativeCrypto.java)
       at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake + 357(OpenSSLSocketImpl.java:357)
       at okhttp3.internal.connection.RealConnection.connectTls + 319(RealConnection.java:319)
       at okhttp3.internal.connection.RealConnection.establishProtocol + 283(RealConnection.java:283)
       at okhttp3.internal.connection.RealConnection.connect + 168(RealConnection.java:168)
       at okhttp3.internal.connection.StreamAllocation.findConnection + 257(StreamAllocation.java:257)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection + 135(StreamAllocation.java:135)
       at okhttp3.internal.connection.StreamAllocation.newStream + 114(StreamAllocation.java:114)
       at okhttp3.internal.connection.ConnectInterceptor.intercept + 42(ConnectInterceptor.java:42)
       at okhttp3.internal.http.RealInterceptorChain.proceed + 147(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed + 121(RealInterceptorChain.java:121)
       at okhttp3.internal.cache.CacheInterceptor.intercept + 93(CacheInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed + 147(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed + 121(RealInterceptorChain.java:121)
       at okhttp3.internal.http.BridgeInterceptor.intercept + 93(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed + 147(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept + 126(RetryAndFollowUpInterceptor.java:126)
       at okhttp3.internal.http.RealInterceptorChain.proceed + 147(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed + 121(RealInterceptorChain.java:121)
       at okhttp3.logging.HttpLoggingInterceptor.intercept + 156(HttpLoggingInterceptor.java:156)
       at okhttp3.internal.http.RealInterceptorChain.proceed + 147(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed + 121(RealInterceptorChain.java:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain + 254(RealCall.java:254)
       at okhttp3.RealCall$AsyncCall.execute + 200(RealCall.java:200)
       at okhttp3.internal.NamedRunnable.run + 32(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1162(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 636(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run + 764(Thread.java:764
````

Android 8, multiple devices, Version 2.7.10-beta.

### PR DESCRIPTION
**Pull request by maniac103**
Closes #1429

### CODE REVIEW

File: mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.kt [hunk 1]
```diff
@@ -318,12 +318,12 @@ class ConnectionFactory internal constructor(
     private class ClientKeyManager(context: Context, private val alias: String?) : X509KeyManager {
         private val context: Context = context.applicationContext
 
-        override fun chooseClientAlias(keyType: Array<String>, issuers: Array<Principal>, socket: Socket): String? {
+        override fun chooseClientAlias(keyType: Array<String>, issuers: Array<Principal>?, socket: Socket?): String? {
```
Comment (mueller-ma) [inline mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.kt]: How can you make sure `keyType` isn't null? I don't see any `@NonNull` in `X509KeyManager`.

File: mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.kt [hunk 2]
```diff
@@ -318,12 +318,12 @@ class ConnectionFactory internal constructor(
...
             Log.d(TAG, "chooseClientAlias - alias: $alias")
             return alias
         }
 
-        override fun chooseServerAlias(keyType: String, issuers: Array<Principal>, socket: Socket): String? {
+        override fun chooseServerAlias(keyType: String, issuers: Array<Principal>?, socket: Socket?): String? {
```
Comment (mueller-ma) [inline mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.kt]: As above.

File: mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.kt (hunk 1 above)
Comment (maniac103) [reply mobile/src/main/java/org/openhab/habdroid/core/connection/ConnectionFactory.kt]: I reviewed the conscrypt sources:

- https://android.googlesource.com/platform/external/conscrypt/+/refs/heads/master/common/src/main/java/org/conscrypt/ConscryptEngine.java#1715
- called by https://android.googlesource.com/platform/external/conscrypt/+/refs/heads/master/common/src/main/java/org/conscrypt/NativeSsl.java#227
- variable comes from https://android.googlesource.com/platform/external/conscrypt/+/refs/heads/master/common/src/main/java/org/conscrypt/NativeSsl.java#214

I'll change it to follow the inferred types though (I just noticed when creating a new X509KeyManager subclass and doing 'Implement methods' in AS, the types are nullable).
